---
 - name: crete users
   hosts: all
   become: yes
   users: 
    - web.hicham.form
    - db.hicham.form
  #Apache 
 - name: install serveur web 
   hosts: webservers
   roles:
    - web
   #Dtabase
 - name: install DataBase
   hosts: db
   roles:
    - database
