---
 - name: crete users
    hosts: all
    become: yes
    remote_user: hicham
    roles:
     - user
  #Apache 
 - name: install serveur web 
    hosts: web
    roles:
     - webserver
   #Dtabase
 - name: install DataBase
    hosts: db
    roles:
     - database
