---
 - name: crete user
   hosts: all
   remote_user: web.hicham.form
   roles:
    - user
 - name: crete user
   hosts: all
   remote_user: db.hicham.form
   roles:
    - user    
  #Apache 
 - name: install serveur web 
   hosts: webservers
   roles:
    - web
   #Dtabase
 - name: install DataBase
   hosts: db
   roles:
    - database
