---

    - name: ajout group
      group:
              name: exam
              state: present

    - name: create user
      user:
            name: exam
            group: "{{ group }}"
            state: present

    - name: add clef ssh
      authorized_key:
              user: "{{ user }}"
              state: present
              key: "{{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}"

    - name: Ajout de "{{ user }}" dans sudo
      template:
              src: sudo.j2
              dest: /etc/sudoers.d/{{ user }}
